### PR TITLE
Jekyll implementation

### PR DESCRIPTION
**Pull request by cbouy**
@GCCR/website I finished implementing Jekyll, can you test this branch locally so we can merge it ?
I added the instructions to do so in the [README ](https://github.com/GCCR/GCCR.github.io/blob/dev/README.MD) file.

This should close issue #4 and solve the vulnerability problem mentioned by GitHub.

@kwcooper If you want to add some news to fill this section up, take a look at [_posts/2020-04-07-covid19-survey.md](https://raw.githubusercontent.com/GCCR/GCCR.github.io/dev/_posts/2020-04-07-covid19-survey.md) for an example.

Checklist before merge:
- [x] members map should be full width instead of full height
- [x] update the README
- [x] disable the "single axis" wheel zoom on the map (solution [here](https://docs.bokeh.org/en/latest/docs/reference/models/tools.html#bokeh.models.tools.WheelZoomTool.zoom_on_axis))
- [x] solve issue #7 
- [x] simplify the update of survey buttons and their layout (for loop and yml)

### CODE REVIEW

**Comment by Huitzilo** [comment]
Hi! Thanks for adding me to this project. I've set up jekyll locally and can confirm that the page looks good on it (MacOS Catalina) - so far I encountered no errors. 

The member map behaves a bit weird, though - scrolling in the lower part of it squeezes the map instead of zooming it. 

Also, not sure if this is known but on small screens (phones) the map is only partly shown (see screenshot). 
image

**Comment by cbouy** [comment]
Thanks for the comments @Huitzilo !

For the zoom issue, it happens when the user zooms whit the mouse on an axis (which I've hidden). It can be useful on standard plots, but on a map it doesn't make sense to keep this default behavior so I'll disable it.

For small screens, I'll try to make the map full width and see how it looks.

**Comment by cbouy** [comment]
Almost ready to merge !!!
Still 2 things on my checklist: update the README, and full-width responsive map.
@Huitzilo I tried my best to make the map responsive to no avail... I think I need your CSS expertise there 😉

**Comment by kwcooper** [comment]
@cbouy @Huitzilo Did you guys manage to fix the members map? 
If so, can we merge this to master tonight?

**Comment by cbouy** [comment]
I couldn't manage to fix it. The map is embeded in an `<iframe>` so I went for [this Bootstrap solution](https://getbootstrap.com/docs/4.4/utilities/embed/) but it doesn't work... 
It's not really a reason to delay the merge further though. If @Huitzilo can confirm that my recent changes work then let's go 👍

**Comment by Huitzilo** [comment]
I had a look at the members map and why it doesn't rescale. Unfortunately I don't have a quick fix either. It seems to be set to fixed width and/or height. Not sure why! Also, I wonder how the html generated with bokeh interferes with the scaling. I'd have to look deeper into how the map is generated. Perhaps bokeh lets one configure responsive behaviour when generating html.  

In the meantime, this shouldn't block the migration to jekyll. The member map display is currently broken for small screens anyway, so the migration won't change this. 

Maybe leave it broken for now and open a separate issue for this? Probably even in https://github.com/GCCR/members-map ?

**Comment by cbouy** [comment]
@Huitzilo You were right, the problem was on the bokeh side ! 
For some unknown reason the aspect ratio isn't quite the same for very small screen (the height is a bit squished) but it's not really noticeable unless you compare original vs small screen.

I guess we're good to merge

**Comment by kwcooper** [comment]
Great all! I'll go ahead and merge! I don't think there will be any issues, but we should all look around the upgraded site to make sure! 

Awesome work everyone! This is going to be so much nicer to work with

**Pull request merged**
