### PR TITLE
Survey table

### LINKED ISSUE #37: on the English language page for the various studies....
Instead of the radiobutton list, we figured that this would work better and make it easier for potential participants to choose the right study: 
Screen Shot 2021-02-24 at 10 54 47 AM

Do you think this can be incorporated? 

I'm copying the text from leadership team below: 

> 

Hi all, a few of us met to clean up the GCCR study recruitment page to reduce potential confusion on the part of our participants. After considering a question wizard ("I want to do...") and a flow chart, we decided on a simple summary table, with links. Screen shots of the existing questions, and the proposed replacement table are attached.
In terms of various languages, our plan is to use this table on the landing pages for the ~13 to 16 languages that have more than one GCCR study available. Languages that do not have multiple studies will never see  this table.
If a specific study is not available in a specific language, it will be retained in the table but grayed out. We fully recognize this will annoy some participants that they cannot do a certain study, but we also thought it was worth this annoyance as it will allow multilingual individuals to chose to do a specific study in another language (e.g., if Marga went to the Dutch page and learned of a study she wanted to do that wasn't available in Dutch, she might chose to do it in English instead.).
Your feedback and/or simple approval are both welcome and desired.

### PR DESCRIPTION
**Pull request by cbouy**
Fixes #37 

I've started working on the table of surveys, here's a quick mockup based on what @mariaveldhuizen sent:
image

We should probably add hover tooltips on each image with a corresponding text description.
I'm not sure if we want to keep the MCQ (below the table) or not (to avoid confusion) ?
@kwcooper this version isn't considering mobiles for now, but we'll have to make the table mobile-friendly at some point.

Also I'll need the URL for the S&T challenge at some point

### CODE REVIEW

**Comment by kwcooper** [comment]
This looks great! 

I wonder if we'll need to add a key of some sort to describe the symbols, or place the text below them. 

Also, how does it look on mobile? 

For the last column, I wonder if we can resize the images so that the columns are the same size, or maybe edit the spacing between them so that they're closer?

In any case, it looks really good so far!

**Comment by mariaveldhuizen** [comment]
I can probably revise the icons in the last column to make them uniform in width. How about for mobile we transpose the table, could that work?

**Comment by mariaveldhuizen** [comment]
Another complication is that the check and challenge both land at the same page. We are looking into two separate links for those, but we want to launch this without waiting (because our new tool is ready for data collection). So I would like to suggest an intermediate solution: 
1.  when clicking the link to the challenge, we will include an intermediate page that shows a screenshot of the button and say " click the top button on the next page that looks like this"
2. same for check, but the intermediate page  the check " click the top button on the next page that looks like this"

I realize this is a super clunky solution, but maybe best in the interest of time? 
button_check
button_challenge

**Comment by mariaveldhuizen** [comment]
This is the actual landing page, to challenge is indeed on the top. https://riech-check.de/

**Comment by cbouy** [comment]
Yes we can have an intermediate window within the page, a bit like with the current setting with the MCQ that opens a popup with the links to the appropriate test(s), except this time there would be images saying "there are several tests so make sure to click on this button".
What I'm a bit more worried is that this riech-check.de page is dependent on the browser's language settings so on the page I might only see one test and not the other ? Or are they both available no matter the language ?

**Comment by mariaveldhuizen** [comment]
YES, THAT can of worms.... So hopefully they will have sorted out different links for the different versions by the time we implement the table for different languages too.... We just want to implement this intermediate solution for English. Because for now we also only need the fourth tool and that extra clarification of the differences between the tools for English mostly.

**Comment by mariaveldhuizen** [comment]
This folder contains the icons for the table. 
Naming is consistent with position in Table.
Column 1 is "focus"
Column 2 is "clock"
Column 3 is "calendar"
Column 4 is "items"

Row 1 is "challenge" (https://riech-check.de/) (separate URL TBA, language based on browser language)
Row 2 is "tracker" (https://is.gd/smellandtastecheck_gccr) (separate links for separate languages)
Row 3 is "check" (https://riech-check.de/) (separate URL TBA, language based on browser language)
Row 4 is "survey" (https://psusensory.compusensecloud.com/edu/showtest.aspx)

So then for the cells [column, row] we want icon with text:
[1,1] focus_challenge.png "awareness"
[1,2] focus_tracker.png "change over time"
[1,3] focus_check.png "loss"
[1,4] focus_survey.png "overall symptoms"

[2,1] clock_challenge.png "under 5 min"
[2,2] clock_tracker.png "15-20 min"
[2,3] clock_check.png "30 min"
[2,4] clock_survey.png "15 min"

[3,1] calendar_challenge.png "daily"
[3,2] calendar_tracker.png "weekly for 7 weeks, and 2 follow-ups later"
[3,3] calendar_check.png "once or more at your own pace"
[3,4] calendar_survey.png "once"

[4,1] items_challenge_combined.png "your own  device and a beverage"
[4,2] items_tracker_combined.png "your own device and regular household items"
[4,3] items_check_combined.png "your own  device and regular household items"
[4,4] items_survey.png "your own  device"
[selected_icons.zip](https://github.com/GCCR/GCCR.github.io/files/6559231/selected_icons.zip)
mock_table

Mock table attached as well as zip folder with all icons.

**Comment by cbouy** [comment]
The table is now responsive to the device width, and the tooltips should appear larger and work on mobile too.
I moved the tooltips content from the `survey.html` file to `en.md` for clarity.
I also fixed the images for the check and the survey which were inverted (survey said 15 min but the clock showed 30 min, and vice versa)

**Comment by mariaveldhuizen** [comment]
this is great! Thanks @cbouy

**Comment by kwcooper** [comment]
well... hopefully this doesn't break anything...

**Pull request merged**
